name: generators

on: workflow_dispatch

jobs:
  generators:
    name: Test generators
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/n3pdf/lhapdf:v2
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          # tags needed for dynamic versioning
          fetch-depth: 0
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true
      - name: Install project
        run: |
          poetry install --no-interaction
      - name: Get pinecards
        run: |
          cd examples && git clone git@github.com:NNPDF/pinecards.git
      - name: Get a theory
        uses: DamianReeves/write-file-action@master
        with:
          path: examples/401.yaml
          write-mode: overwrite
          contents: |
          ID: 401
          Comments: NNPDF4.0 NLO alphas=0.118 with new pipeline, scalevaried (xif = 1.0, xir = 1.0) scheme B
          CKM: 0.97428 0.22530 0.003470 0.22520 0.97345 0.041000 0.00862 0.04030 0.999152
          DAMP: 0
          EScaleVar: 1
          FNS: FONLL-B
          GF: 1.1663787e-05
          HQ: POLE
          IC: 1
          IB: 0
          MP: 0.938
          MW: 80.398
          MZ: 91.1876
          MaxNfAs: 5
          MaxNfPdf: 5
          ModEv: TRN
          ModSV: None
          NfFF: 4
          PTO: 1
          Q0: 1.65
          QED: 0
          Qedref: 1.777
          Qmb: 4.92
          Qmc: 1.51
          Qmt: 172.5
          Qref: 91.2
          SIN2TW: 0.23126
          SxOrd: LL
          SxRes: 0
          TMC: 1
          XIF: 1.0
          XIR: 1.0
          alphaqed: 0.007496252
          alphas: 0.118
          global_nx: 0
          kbThr: 4.0
          kcThr: 1.0
          ktThr: 1.0
          mb: 4.92
          mc: 1.51
          mt: 172.5
          nfref: null
          nf0: null
          kDIScThr: 1.0
          kDISbThr: 4.0
          kDIStThr: 1.0
          RenScaleVar: true
          FactScaleVar: true
      - name: Execute all generators
        run: |
          # positivity
          pinefarm run NNPDF_POS_F2U_40 examples/401.yaml
          # yadism
          # pinefarm run HERA_CC_318GEV_EM_SIGMARED examples/401.yaml
