name: generators

on:
  push:
  workflow_dispatch:

jobs:
  generators:
    name: Test generators
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/n3pdf/lhapdf:v2
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true
      - name: Install project
        run: |
          poetry install --no-interaction
      - name: Get pinecards
        uses: actions/checkout@v2
        with:
          repository: NNPDF/pinecards
          path: examples/
      - name: Execute all generators
        run: |
          ls -l
          ls -l examples/
          ls -l ../
          # ls -l examples/pinecards
          ls -l pinecards/
          mv examples/pinecards/* examples/
          # positivity
          pinefarm run NNPDF_POS_F2U_40 benchmarks/data/401.yaml
          # yadism
          # pinefarm run HERA_CC_318GEV_EM_SIGMARED .github/bench_data/401.yaml
