name: generators

on: workflow_dispatch

jobs:
  generators:
    name: Test generators
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/n3pdf/lhapdf:v2
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true
      - name: Install project
        run: |
          poetry install --no-interaction -E complete
